zad1:
	flex -o test.c zadanie1.l
	gcc test.c -O3 -lfl -o test

zad2:
	flex -o test.c zadanie2.l
	gcc test.c -O3 -lfl -o test

zad3:
	flex -o test.c zadanie3.l
	gcc test.c -O3 -lfl -o test

zad4:
	flex -o test.c zadanie4.l
	gcc test.c -O3 -lfl -lm -o test

clean:
	rm test.c test